language: python
python:
  - "2.7"
notifications:
  email: false
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r dev-requirements.txt --use-mirrors"
script: py.test -n 4
